
package aex.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MockEffectenBeursService", targetNamespace = "http://server.aex/", wsdlLocation = "http://localhost:8080/Fondsen?wsdl")
public class MockEffectenBeursService
    extends Service
{

    private final static URL MOCKEFFECTENBEURSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MOCKEFFECTENBEURSSERVICE_EXCEPTION;
    private final static QName MOCKEFFECTENBEURSSERVICE_QNAME = new QName("http://server.aex/", "MockEffectenBeursService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Fondsen?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MOCKEFFECTENBEURSSERVICE_WSDL_LOCATION = url;
        MOCKEFFECTENBEURSSERVICE_EXCEPTION = e;
    }

    public MockEffectenBeursService() {
        super(__getWsdlLocation(), MOCKEFFECTENBEURSSERVICE_QNAME);
    }

    public MockEffectenBeursService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MOCKEFFECTENBEURSSERVICE_QNAME, features);
    }

    public MockEffectenBeursService(URL wsdlLocation) {
        super(wsdlLocation, MOCKEFFECTENBEURSSERVICE_QNAME);
    }

    public MockEffectenBeursService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MOCKEFFECTENBEURSSERVICE_QNAME, features);
    }

    public MockEffectenBeursService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MockEffectenBeursService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MockEffectenBeurs
     */
    @WebEndpoint(name = "MockEffectenBeursPort")
    public MockEffectenBeurs getMockEffectenBeursPort() {
        return super.getPort(new QName("http://server.aex/", "MockEffectenBeursPort"), MockEffectenBeurs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MockEffectenBeurs
     */
    @WebEndpoint(name = "MockEffectenBeursPort")
    public MockEffectenBeurs getMockEffectenBeursPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.aex/", "MockEffectenBeursPort"), MockEffectenBeurs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MOCKEFFECTENBEURSSERVICE_EXCEPTION!= null) {
            throw MOCKEFFECTENBEURSSERVICE_EXCEPTION;
        }
        return MOCKEFFECTENBEURSSERVICE_WSDL_LOCATION;
    }

}
