
package aex.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MockEffectenBeurs", targetNamespace = "http://server.aex/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MockEffectenBeurs {


    /**
     * 
     * @return
     *     returns java.util.List<aex.client.Fonds>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "koersen", targetNamespace = "http://server.aex/", className = "aex.client.Koersen")
    @ResponseWrapper(localName = "koersenResponse", targetNamespace = "http://server.aex/", className = "aex.client.KoersenResponse")
    @Action(input = "http://server.aex/MockEffectenBeurs/koersenRequest", output = "http://server.aex/MockEffectenBeurs/koersenResponse")
    public List<Fonds> koersen();

}
